@startuml
class main.java.com.poyrazaktas.multi_thread_safe_singleton_object_pool_pattern.Car {
- int id
- String rentedBy
- Date rentDate
- Date returnDate
+ String getRentedBy()
+ void setRentedBy(String)
+ Date getRentDate()
+ void setRentDate(Date)
+ Date getReturnDate()
+ void setReturnDate(Date)
}
@enduml